[package]
name = "sd-cloud-api"
version = "0.1.0"
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
sd-p2p = { path = "../p2p" }
reqwest = "0.11.22"
serde.workspace = true
serde_json.workspace = true
thiserror = "1.0.50"
uuid.workspace = true
rspc = { workspace = true }
specta.workspace = true
base64.workspace = true
